apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: system-critical
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: lyon-cluster-ebs20
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: [ "m" ]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: [ "2", "4" ]
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values: [ "nitro" ]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: [ "2" ]
        - key: kubernetes.io/arch
          operator: In
          values: [ "amd64", "arm64" ]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [ "on-demand", "spot" ]
        - key: eks.amazonaws.com/nodegroup
          operator: In
          values: [ "system-critical" ]
      taints:
        - effect: NoSchedule
          key: system-critical
          value: "yes"