apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # specific provisioners by instance-type
  - provisioners/m5-ebs50.yaml
  - provisioners/c5-ebs20.yaml
  - provisioners/c5-ebs50.yaml
  # test server provisioner (test-1~4, seo, tm, qa, design ...)
  - provisioners/test.yaml