apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ m5 ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ medium, large ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ on-demand ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ default ]
#  ttlSecondsUntilExpired: 604800
#  ttlSecondsAfterEmpty: 60
  consolidation:
    enabled: true
  weight: 10
  providerRef:
    name: lyon-cluster-ebs30