apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-provisioning
  name: init-provisioning
  namespace: default
spec:
  replicas: 100
  selector:
    matchLabels:
      app: init-provisioning
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-evict: "true"
      labels:
        app: init-provisioning
    spec:
      containers:
        - name: nginx
          image: nginx:1.16-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 1500m
              memory: 6Gi
      nodeSelector:
        eks.amazonaws.com/nodegroup: default