apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: cron
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: lyon-cluster-ebs30
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c5
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - large
            - xlarge
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-northeast-2a
            - ap-northeast-2c
        - key: eks.amazonaws.com/nodegroup
          operator: In
          values:
            - cron
      taints:
        - effect: NoSchedule
          key: system-type
          value: cron
  weight: 10
