apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../base/charts/

helmCharts:
  - name: nodegroups
    releaseName: nodegroups
    includeCRDs: false
    valuesFile: ../../base/nodegroups.yaml
    additionalValuesFiles:
      - patches/patch-nodegroups.yaml

patches:
  - target:
      kind: Deployment
      name: karpenter
    path: patches/patch-deployment.yaml
  - target:
      kind: ServiceAccount
    path: patches/patch-service-account.yaml
