apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-global-settings
  namespace: karpenter
data:
  "aws.assumeRoleARN": ""
  "aws.assumeRoleDuration": "15m"
  "aws.clusterCABundle": ""
  "aws.clusterEndpoint": ""
  "aws.clusterName": "lyon-cluster-platform"
  "aws.defaultInstanceProfile": "KarpenterNodeInstanceProfile-lyon-cluster-platform"
  "aws.enableENILimitedPodDensity": "true"
  "aws.enablePodENI": "false"
  "aws.interruptionQueueName": "lyon-cluster-platform"
  "aws.isolatedVPC": "false"
  "aws.vmMemoryOverheadPercent": "0.075"
  "batchIdleDuration": "1s"
  "batchMaxDuration": "10s"
  "featureGates.driftEnabled": "false"