apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: lyon-cluster*
spec:
  amiFamily: AL2
  role: KarpenterNodeRole-lyon-cluster-platform
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "lyon-cluster-platform"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "lyon-cluster"
  metadataOptions:
    httpTokens: optional