apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: lyon-cluster*
spec:
  amiFamily: AL2
  role: lyon-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: lyon-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: lyon-cluster
  tags:
    karpenter.sh/discovery: lyon-cluster