apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: service-arm64
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    metadata: {}
    spec:
      nodeClassRef:
        name: lyon-cluster-ebs20
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - t4g
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - medium
            - large
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-northeast-2a
            - ap-northeast-2c
        - key: eks.amazonaws.com/nodegroup
          operator: In
          values:
            - platform
            - lyon-gateway
      taints:
        - effect: NoSchedule
          key: system-type
          value: service
  weight: 10
