apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: m5-ebs50
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ m5 ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ large, xlarge ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ on-demand ]
    - key: kubernetes.io/arch
      operator: In
      values: [ amd64 ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ m5-service, apigateway ]
  consolidation:
    enabled: true
  weight: 10
  providerRef:
    name: lyon-cluster-ebs50
  taints:
    - key: system-type
      effect: NoSchedule
      value: service