apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ m5, t3 ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ large, xlarge ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ spot ]
    - key: kubernetes.io/arch
      operator: In
      values: [ amd64 ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ test ]
  ttlSecondsUntilExpired: 604800
  consolidation:
    enabled: true
  weight: 10
  providerRef:
    name: lyon-cluster-ebs20