apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: cicd-arm64
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ c6g ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ xlarge ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ on-demand ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ cicd ]
  ttlSecondsAfterEmpty: 60
  weight: 10
  providerRef:
    name: lyon-cluster-ebs20
  taints:
    - key: system-type
      effect: NoSchedule
      value: cicd