apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-arm64
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ m6g ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ large, xlarge ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ default ]
  consolidation:
    enabled: true
  weight: 10
  providerRef:
    name: lyon-cluster-ebs30
  taints:
    - key: system-type
      effect: NoSchedule
      value: default