apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: lyon-cluster*
spec:
  securityGroupSelector:
    karpenter.sh/discovery: "lyon-cluster-staging"
  subnetSelector:
    aws-ids: "subnet-XXXXXXXXXXXXXXXXX, subnet-XXXXXXXXXXXXXXXXX"
  metadataOptions:
    httpTokens: optional