apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-global-settings
  namespace: karpenter
data:
  "aws.clusterEndpoint": ""
  "aws.clusterName": "lyon-cluster-staging"
  "aws.defaultInstanceProfile": "KarpenterNodeInstanceProfile-lyon-cluster-staging"
  "aws.enableENILimitedPodDensity": "true"
  "aws.enablePodENI": "false"
  "aws.interruptionQueueName": ""
  "aws.isolatedVPC": "false"
  "aws.vmMemoryOverheadPercent": "0.075"
  "batchIdleDuration": "1s"
  "batchMaxDuration": "10s"
  "featureGates.driftEnabled": "false"