apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spot-default
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [t3, t3a]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [medium, large, xlarge]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ap-northeast-2a, ap-northeast-2c]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [spot]
    - key: capacity-spread
      operator: In
      values: ["2", "3", "4", "5"]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values:
        - default
  ttlSecondsUntilExpired: 604800
  ttlSecondsAfterEmpty: 3000
  weight: 10
  providerRef:
    name: lyon-cluster-platform