apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: system-critical
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ t3 ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ medium, large, xlarge ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ system-critical ]
  ttlSecondsAfterEmpty: 600
  weight: 10
  providerRef:
    name: lyon-cluster-ebs20
  taints:
    - key: system-critical
      effect: NoSchedule
      value: yes
  labels:
    system-critical: yes