apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: service
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ m5 ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ large, xlarge ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ on-demand ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ account-service, ad-service, cash-service,
                provider-service, quote-service, request-service, service-service,
                frontend ]
  ttlSecondsAfterEmpty: 60
  weight: 10
  providerRef:
    name: lyon-cluster-ebs20
  taints:
    - key: system-type
      effect: NoSchedule
      value: service