apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: monitoring
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [ r5 ]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [ large ]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ ap-northeast-2a, ap-northeast-2c ]
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values: [ monitoring ]
  ttlSecondsAfterEmpty: 60
  weight: 10
  providerRef:
    name: lyon-cluster-ebs20